#!/bin/bash

# This script sets up Android SDK in any Linux environment
# Usage: bash setup-android-sdk.sh

set -e

echo "ðŸš€ Installing Android SDK..."

# Install Java if not present
if ! command -v java &> /dev/null; then
    echo "ðŸ“¦ Installing OpenJDK 17..."
    apt-get update
    apt-get install -y openjdk-17-jdk
fi

# Set Android SDK location
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME

# Create directory
mkdir -p $ANDROID_HOME

# Download command line tools
echo "â¬‡ï¸  Downloading Android Command Line Tools..."
cd /tmp
wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
unzip -q commandlinetools-linux-11076708_latest.zip -d $ANDROID_HOME
rm commandlinetools-linux-11076708_latest.zip

# Reorganize cmdline-tools
mkdir -p $ANDROID_HOME/cmdline-tools/latest
cd $ANDROID_HOME/cmdline-tools
mv bin lib latest/
cd latest
ls -la

# Add to PATH
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/build-tools/34.0.0

# Accept licenses
echo "ðŸ“ Accepting licenses..."
yes | sdkmanager --licenses || true

# Install essential packages
echo "ðŸ“¦ Installing SDK packages..."
sdkmanager --install \
    "platform-tools" \
    "platforms;android-34" \
    "platforms;android-33" \
    "build-tools;34.0.0" \
    "build-tools;33.0.0" \
    "emulator" \
    "system-images;android-34;google_apis;x86_64"

# Add exports to shell profile
echo "" >> ~/.bashrc
echo "# Android SDK" >> ~/.bashrc
echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc
echo "export ANDROID_SDK_ROOT=$ANDROID_HOME" >> ~/.bashrc
echo "export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin" >> ~/.bashrc
echo "export PATH=\$PATH:\$ANDROID_HOME/platform-tools" >> ~/.bashrc
echo "export PATH=\$PATH:\$ANDROID_HOME/build-tools/34.0.0" >> ~/.bashrc
echo "export PATH=\$PATH:\$ANDROID_HOME/emulator" >> ~/.bashrc

# For zsh users
if [ -f ~/.zshrc ]; then
    echo "" >> ~/.zshrc
    echo "# Android SDK" >> ~/.zshrc
    echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.zshrc
    echo "export ANDROID_SDK_ROOT=$ANDROID_HOME" >> ~/.zshrc
    echo "export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin" >> ~/.zshrc
    echo "export PATH=\$PATH:\$ANDROID_HOME/platform-tools" >> ~/.zshrc
    echo "export PATH=\$PATH:\$ANDROID_HOME/build-tools/34.0.0" >> ~/.zshrc
    echo "export PATH=\$PATH:\$ANDROID_HOME/emulator" >> ~/.zshrc
fi

echo "âœ… Android SDK installed successfully!"
echo ""
echo "ðŸ“ ANDROID_HOME: $ANDROID_HOME"
echo ""
echo "ðŸ”„ To apply changes, run: source ~/.bashrc"
echo ""
echo "âœ¨ Verify installation:"
echo "   adb --version"
echo "   sdkmanager --list"

# ============================================
# FILE: local.properties.example
# ============================================
# This file is automatically generated by the setup script
# DO NOT commit this file to git (add to .gitignore)

sdk.dir=/opt/android-sdk
# or on local machine:
# sdk.dir=/home/username/Android/Sdk